name: Tests

on:
  push:
    paths:
      - "**/*.ts"
      - "**/*.tsx"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bunx prisma generate
        env:
          DATABASE_URL: "file:./test.db"

      - name: Reset DB and apply schema
        run: bunx prisma migrate reset --force --skip-seed
        env:
          DATABASE_URL: "file:./test.db"

      # Start backend server in the background
      - name: Start backend server
        run:  |
          bun run app/server.ts &
          echo $! > server.pid
        env:
          NODE_ENV: test
          DATABASE_URL: 'file:./test.db'
        continue-on-error: false

      # Wait for the server to respond on port 3000
      - name: Waif for API to be ready
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:3000/v1/trpc/bugs.getBugs > /dev/null; then
              echo 'Server is running'
              break
            fi
            echo ' Waiting for server...'
            sleep 2
          done

      - name: Run tests
        run: bun test
        env:
          DATABASE_URL: "file:./test.db"

      - name: Stop backend server
        if: always()
        run: kill $(cat server.pid) || true
